version: "3.5"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: pawatask
      MYSQL_USER: pawa
      MYSQL_PASSWORD: pawa
      MYSQL_ROOT_PASSWORD: pawa
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/frontend
      - /usr/front/node_modules
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - NODE_ENV=development
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - frontend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/pawatask?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pawa
