### Task

GET http://localhost:8080/api/tasks/
Accept: application/json

###

POST http://localhost:8080/api/tasks/
Content-Type: application/json

{
  "title": "Start Project",
  "description": "Nature picture challenge TV. Opportunity recently fight war. Book forward reduce charge.",
  "status": true,
  "priority": "normal",
  "dueDate": "Mon, 06 May 2019 12:59:17 +0300",
  "comments": [
    {
      "text": "First",
      "date": "Mon, 04 May 2019 10:59:17 +0300"
    },
    {
      "text": "Second",
      "date": "Mon, 05 May 2019 16:29:17 +0300"
    }
  ]
}

###

GET http://localhost:8080/api/tasks/2
Accept: application/json

###

PUT http://localhost:8080/api/tasks/
Content-Type: application/json

{
  "id": "1",
  "title": "End Project",
  "description": "Nature picture challenge TV. Opportunity recently fight war. Book forward reduce charge.",
  "status": true,
  "priority": "high",
  "dueDate": "Mon, 06 May 2029 12:59:17 +0300",
  "comments": [
    {
      "id": 2,
      "text": "Second",
      "date": "Mon, 04 May 2029 10:59:17 +0300"
    },
    {
      "id": 3,
      "text": "Dozen",
      "date": "Mon, 05 May 2029 16:29:17 +0300"
    }
  ]
}

###

DELETE http://localhost:8080/api/tasks/1

### Comment

PUT http://localhost:8080/api/comments/
Content-Type: application/json

{
  "id": 2,
  "text": "I'm Second!",
  "date": "Mon, 05 May 3019 16:29:17 +0300"
}

###

DELETE http://localhost:8080/api/comments/4

###

POST http://localhost:8080/api/tasks/1/comments
Content-Type: application/json

{
  "text": "I'm new!",
  "date": "Mon, 05 May 2119 16:29:17 +0300"
}

###
